### PR TITLE
Add spanish language files. Translated by me.

### PR DESCRIPTION
**Pull request by jonaspm**
Add spanish translation.

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Hi @jonaspm, thanks for doing the spanish translation on the TB file.  

On the #537 issue, sorry, the source code in " Attic/AtomicEditorReference" is the original editor, which was in C++ and is currently in the repo solely for reference.  The editor is now in TypeScript with the sources here:

https://github.com/AtomicGameEngine/AtomicGameEngine/tree/master/Script/AtomicEditor

I can land the PR, though if you're interested in fixing #537, it would need to be in script and tested.

**Comment by jonaspm** [comment]
Thanks for pointing that out Josh, I'll try again.

**Comment by JoshEngebretson** [comment]
Landing, please file a new issue if you address/test the #537 enhancement

**Comment by jonaspm** [comment]
Hi Josh, I have been having trouble building AtomicGameEngine with VS2015, the build process generates many warnings and errors than no libs were found.

**Comment by JoshEngebretson** [comment]
Hey, so this is probably related to the CEF submodule using a relative path... I just updated it, please try pulling fresh and init-ing submodules

**Comment by jonaspm** [comment]
[solutionerrorlog.txt](https://github.com/AtomicGameEngine/AtomicGameEngine/files/118295/solutionerrorlog.txt)

**Comment by JoshEngebretson** [comment]
Correct, you need to checkout or initial submodules:

git clone --recursive https://github.com/AtomicGameEngine/AtomicGameEngine

**Pull request merged**
