### PR TITLE
Per project extensions, authors update

### PR DESCRIPTION
**Pull request by mattbenic**
This PR provides the ability to have .plugin.js files in the <Project>/Resources/EditorData directory that are loaded when the project is opened. These plugins can currently add plugin menu items, respond to widget events and open modal windows.

Thanks to @shaddockh for better encapsulating the plugin loading in a new service.

Also, a long overdue addition of @JohnnyWahib and @Vlamboljant to the authors file.

### CODE REVIEW

**Comment by mattbenic** [comment]
@JoshEngebretson this build failure seems to be because of the CI server being down. This is the second time I've seen this recently, is it a new server you're trying out?

**Comment by JoshEngebretson** [comment]
@mattbenic : The CI server hasn't been down, it is now behind our firewall for security reasons due to increased traffic.  Need a solution for getting errors reported, other than ctrl-c, ctrl-v :) 

The Linux build failed:

[Tue Apr 12 01:27:04 2016] INFO: Loading Module: /var/lib/jenkins/jobs/AtomicDS_BuildBinaries_Linux/workspace/Script/Packages/WebView/WebView.json
[Tue Apr 12 01:27:04 2016] INFO: Generating JS Bindings
[Tue Apr 12 01:27:04 2016] INFO: Generating C# Bindings
Script/TypeScript/AtomicWork.d.ts(5,1): error TS6053: File 'Script/TypeScript/AtomicNet.d.ts' not found.
jake aborted.

**Comment by JoshEngebretson** [comment]
Linux catching a case issue somewhere on the .NET stuff, the file on the file system is: AtomicNET.d.ts

**Comment by mattbenic** [comment]
Ah damn, sorry about that. Fixing.

**Comment by JoshEngebretson** [comment]
... aaaaand passing on CI, thanks!

This is darned cool, looking forward to checking it out :)

**Comment by shaddockh** [comment]
@JoshEngebretson, you can see an example and more information at:  https://github.com/LumaDigital/AtomicGameEngine/pull/2 .  Once this lands, an example in AtomicExamples needs to be created.

**Comment by JoshEngebretson** [comment]
This is wonderful stuff, great code architecture.  Very happy to see @shaddockh's new service stuff useful so immediately, great job all.  LANDING!  

@shaddockh Does that example usage in https://github.com/LumaDigital/AtomicGameEngine/pull/2 exist as a project somewhere that can be brought into AtomicExamples?  We're going to be staring the need for unit tests in the eyes pretty soon here too... *insert dramatic string hit*

**Comment by shaddockh** [comment]
I understand @mattbenic has been using it to build out an internal plugin.  If he doesn't have anything that he can readily share, I can throw together a simple example some time this week.  The one in  https://github.com/LumaDigital/AtomicGameEngine/pull/2 was just something that I modified from what @mattbenic had.  For an example, I'm thinking that something that illustrates how to write an extension in pure javascript and one in typescript would be good.

Unit tests.  *shudder* .  I know that they need to be done, but it's going to be really interesting to figure out how to do.  I think the purely functional tests for the TypeScript could be done with mocha or jasmine pretty easily, but the ones that need to interact with the runtime might pose a challenge...this is where AtomicCli will probably need brought up to speed.

**Comment by mattbenic** [comment]
I can sanitize the part of our plugin that registers itself, adds a plugins menu item and shows a modal dialog with some controls. That's why I was asking about how the .d.ts files are handled after the initial project template is copied :) For now manual update is fine but at some point that needs to be done from a menu option or something ("Upgrade project to latest format").

Do we need a separate javascript example? The TS compiles out to js and that's what actually gets consumed when the plugin is loaded. So the TS example would necessarily include the ts script and it's compiled form.

**Comment by shaddockh** [comment]
The only reason I was thinking a pure javascript example is for those people that don't want to go down the typescript route.  Also, I think a hand-written JS example wouldn't have all the ceremony that the transpiled TS emits.  What I may try to do is attempt to rewrite the  TS example you provided in simpler JS and see what it looks like and if it looks pretty good, submit a followup PR.

**Comment by mattbenic** [comment]
By all means :)

**Pull request merged**
