### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by rokups**
Commit https://github.com/urho3d/Urho3D/commit/129205a9b1fd94573c81feba76f897990990e8ec

Did not update SystemUI, Console and DebugHud because they are on the way out.
Urho3D added IK 🎉 
Also updated some third party libs. Good news - custom modifications for includes no longer needed because we have a sane build scripts ;)
Few changes were available upstream so i removed `// ATOMIC BEGIN|END`.
Did my best though there still might be some hairy stuff.

~~[This](https://github.com/AtomicGameEngine/AtomicGameEngine/compare/master...rokups:feature/sync-with-upstream?expand=1#diff-8ef915a919ab0b16a1fe463c9fd93113R607) breaks binding generation. Suddenly `createNode()` in TS becomes unavailable.~~
Removed [this](https://github.com/AtomicGameEngine/AtomicGameEngine/compare/master...rokups:feature/sync-with-upstream?expand=1#diff-f8512b2d79defbf65ead65f19a2cbd19L30) because similar types are now part of rapidjson, please verify if it was a valid decision.

Let the buildbot games begin 🥇

### CODE REVIEW

**Comment by rokups** [comment]
@JoshEngebretson requesting assistence regarding windows build error:

    C:\Jenkins\workspace\AtomicPR_Windows\Script\AtomicNET\AtomicNET\IO\File.cs(7,42): error CS0535: 'File' does not implement interface member 'Deserializer.Eof' [C:\Jenkins\workspace\AtomicPR_Windows\Artifacts\AtomicNET\Build\AtomicNET\AtomicNET.csproj]

This most likely happens because of new base class for `File`. Now `File` inherits `AbstractFile` which is simply inherits `Serializer` and `Deserializer`. I tried to make that reflect in `Script\AtomicNET\AtomicNET\IO` but looks like it does not work. Please advice.

**Comment by JoshEngebretson** [comment]
If you pull this into the branch, should build: https://github.com/AtomicGameEngine/AtomicGameEngine/tree/JME-ATOMIC-SYNCUPSTREAM

I was able to create a new JS/C# basic 3D project and run them, the C# mutant example (which uses physics crashed).  I didn't run through the FeatureExamples yet.

>This breaks binding generation. Suddenly createNode() in TS becomes unavailable.
>Removed this because similar types are now part of rapidjson, please verify if it was a valid decision.```

The two "this" links go to a bunch of diff, wondering on the rapidjson, have a better link?  The createNode issue should be sorted.

**Comment by rokups** [comment]
Thank you!

I went through FeatureExamples - they all work. One problem was due to changes from upstream pressing escape quit application instead of resuming to menu. Long story short - on escape press sample initiated menu, menu subscribed to escape key event and newly subscribed handler was invoked for currently executing event. I added a [workaround](https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1519/commits/50a7a5a117f59cd1c4254b9d75e8a2edd4ea7921), please verify if it is ok.

Something odd is going on with c# - for me it crashes due to `
csb_AtomicNETNative_NETCore_GetContext_5090` being missing. I could find said function in `CSModuleAtomicNETNative.cpp` and i cant quite tell what is going on. I will have to ask for your assistance again as you i know next to nothing on how bindings work.

**Comment by JoshEngebretson** [comment]
Ok, https://github.com/AtomicGameEngine/AtomicGameEngine/tree/JME-ATOMIC-UPDATESDL updates SDL to 2.0.5 

I have tested on Windows and Mac, I plan on getting Android and iOS updated and tested tomorrow.  If you could try building on Linux that would be great, ```./Build_AtomicEditor.sh``` is a good test too, making sure the editor binary runs

I'd like to address the event issue another way, probably in the examples, would be good to be consistent with upstream on event handling... and on the C# binding issue, it means that the binary that was loaded was likely out of date.  The native methods are consumed by C FFI, so all functions are assigned an ordinal, to support overloaded methods and help guard against accidentally using incompatible native and managed assembly.

**Comment by rokups** [comment]
@JoshEngebretson that c# issue indeed was resolved by updating .so with latest compiled one. Turns out editor copies .so into game dir and that got out of date quick.

As you can see linux builds but android still fails. Cant get log - please take a peek there.

Also i know why mutant demo crashes, but do not know how to fix it. On [this](https://github.com/AtomicGameEngine/AtomicExamples/blob/master/AtomicMutant/CSharp/Resources/Components/CharacterExample.cs#L28) line it calls `StaticModel::SetModel()` instead of `AnimatedModel::SetModel()`. Because of that [GetChild()](https://github.com/AtomicGameEngine/AtomicExamples/blob/master/AtomicMutant/CSharp/Resources/Components/CharacterExample.cs#L110) returns `null` and application crashes. I cant quite tell why that is. Please advice.

**Comment by JoshEngebretson** [comment]
I'll be looking over the entire delta, squashing, etc.  Don't worry about the mutant and event issue, I'll look into them.

Android is building, I believe iOS AtomicNET native needs to link with AudioToolbox framework too: https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1519/commits/9da0435fa1985bd5a34d66884070fa86c29b65d5#diff-879e9fbcc8991c6492ad92fa24fee6a0R40

```
iphoneos/AtomicNETNative.build/Objects-normal/arm64/AtomicNETNative
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in libSDL.a(SDL_coreaudio.o)
  "_AVAudioSessionCategoryRecord", referenced from:
      _update_audio_session in libSDL.a(SDL_coreaudio.o)
  "_AVAudioSessionInterruptionTypeKey", referenced from:
      -[SDLInterruptionListener audioSessionInterruption:] in libSDL.a(SDL_coreaudio.o)
  "_AVAudioSessionCategoryAmbient", referenced from:
      _update_audio_session in libSDL.a(SDL_coreaudio.o)
  "_AVAudioSessionCategoryPlayAndRecord", referenced from:
      _update_audio_session in libSDL.a(SDL_coreaudio.o)
  "_AVAudioSessionInterruptionNotification", referenced from:
      _update_audio_session in libSDL.a(SDL_coreaudio.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The log is huge due to every compile for Mac/iOS file is spamming console, need to see if possible for less verbosity:

```
CompileC Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/Objects-normal/x86_64/SymbolVisitor.o Source/ToolCore/JSBind/cplusplus/SymbolVisitor.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Release\" -DATOMIC_XCODE -DATOMIC_ROOT_SOURCE_DIR=\"/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android\" -DATOMIC_ROOT_BUILD_DIR=\"/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac\" -DATOMIC_WEBVIEW -DCPLUSPLUS_WITHOUT_QT -DPOCO_NO_AUTOMATIC_LIBS=1 -DPOCO_STATIC=1 -DATOMIC_CXX11=1 -DATOMIC_64BIT=1 -DATOMIC_PLATFORM_OSX=1 -DATOMIC_OPENGL=1 -DATOMIC_PLATFORM_DESKTOP=1 -DATOMIC_FILEWATCHER=1 -DATOMIC_THREADING=1 -DATOMIC_NETWORK=1 -DATOMIC_WEB=1 -DATOMIC_PROFILING=1 -DATOMIC_LOGGING=1 -DATOMIC_3D -DATOMIC_ATOMIC2D=1 -DATOMIC_PHYSICS=1 -DATOMIC_NAVIGATION=1 -DATOMIC_STATIC_DEFINE=1 -DATOMIC_API= -DATOMIC_IK=1 -DCURL_STATICLIB=1 -DKNET_UNIX -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.7 -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Release/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Submodules/CEF/MacOSX -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Assimp/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Poco/Foundation/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/Atomic/.. -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Box2D -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/TurboBadger -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/FreeType/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/JO -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/LZ4 -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/PugiXml/src -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/STB -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/STB/../.. -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ThirdParty/SDL/include/generated -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/SDL/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/ASIO/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/rapidjson/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/WebSocketPP/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/GLEW -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/LibCpuId/src -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/libcurl/lib/../include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/zlib -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Civetweb/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/kNet/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Bullet/src -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/StanHull -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Recast/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/Detour/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/DetourCrowd/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/DetourCrowd/../Detour/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/DetourTileCache/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/DetourTileCache/../Detour/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ThirdParty/ik/include/generated -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ThirdParty/ik/include -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/DerivedSources/x86_64 -I/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Release -Wno-invalid-offsetof -std=gnu++11 -stdlib=libc++ -DNDEBUG -MMD -MT dependencies -MF /Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/Objects-normal/x86_64/SymbolVisitor.d --serialize-diagnostics /Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/Objects-normal/x86_64/SymbolVisitor.dia -c /Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Source/ToolCore/JSBind/cplusplus/SymbolVisitor.cpp -o /Users/jenkins/Home/workspace/AtomicPR_MacEditor_iOS_Android/Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/Objects-normal/x86_64/SymbolVisitor.o
```

**Comment by rokups** [comment]
Urho3D has this for warnings:

```cmake
# When performing Xcode CI build suppress all the warnings for 3rd party libraries because there are just too many of them
if (XCODE AND DEFINED ENV{CI})
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -w")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w")
endif ()
```

**Comment by JoshEngebretson** [comment]
Great eye for detail on pulling the updates from Urho and Third Party deps! 🦅

I am finishing up in this branch and will land from there: https://github.com/AtomicGameEngine/AtomicGameEngine/tree/JME-ATOMIC-URHO_THIRDPARTY_UPDATE

On behalf of 🐫 everywhere, THANKS! 🎉

**Pull request closed without merging**
