### PR TITLE
Stop crash from null objects at exit 248

### PR DESCRIPTION
**Pull request by JimMarlowe**
This pr will stop crashes from accessing null objects in user event handlers by not issuing Update events once the application has started to exit.

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
"by not issuing Update events once the application has started to exit", this doesn't seem quite accurate as we're early exiting from void Engine::Update() and void Engine::Render() instead of not issuing the event

Can we detect this earlier and avoid these (and other) events instead, what does a callstack look like when a null object is encountered, is it easy to reproduce and get one?

**Comment by JimMarlowe** [comment]
exiting_ gets asserted sometime between frames 10 & 11...

```Breakpoint 1, duk_hobject_getprop (thr=0x32fc320, tv_obj=0x7fffffffcda0, tv_key=0x7fffffffcdb0) at duk_hobject_props.c:2258
2258	duk_hobject_props.c: No such file or directory.
(gdb) where
#0  duk_hobject_getprop (thr=0x32fc320, tv_obj=0x7fffffffcda0, tv_key=0x7fffffffcdb0) at duk_hobject_props.c:2258
#1  0x00000000017efcae in duk__js_execute_bytecode_inner (entry_thread=0x32fc320, entry_callstack_top=1) at duk_js_executor.c:3040
#2  0x00000000017edfee in duk_js_execute_bytecode (exec_thr=0x32fc320) at duk_js_executor.c:2068
#3  0x00000000017e03a3 in duk__handle_call_inner (thr=0x32fc320, num_stack_args=1, call_flags=0, idx_func=3) at duk_js_call.c:1580
#4  0x00000000017dfac1 in duk_handle_call_protected (thr=0x32fc320, num_stack_args=1, call_flags=0) at duk_js_call.c:1062
#5  0x00000000017b17f1 in duk_pcall (ctx=0x32fc320, nargs=1) at duk_api_call.c:134
#6  0x000000000122a15d in Atomic::JSEventHelper::HandleEvent (this=0x3588930, eventType=..., eventData=...)
    at /home/val/AGE/AtomicGameEngine/Source/AtomicJS/Javascript/JSEventHelper.cpp:190
#7  0x000000000122b836 in Atomic::EventHandlerImpl<Atomic::JSEventHelper>::Invoke (this=0x3589470, eventData=...)
    at /home/val/AGE/AtomicGameEngine/Source/Atomic/UI/../Core/Object.h:341
#8  0x0000000001393ca9 in Atomic::Object::OnEvent (this=0x3582d80, sender=0x2ef0c60, eventType=..., eventData=...)
    at /home/val/AGE/AtomicGameEngine/Source/Atomic/Core/Object.cpp:121
#9  0x0000000001394a3a in Atomic::Object::SendEvent (this=0x2ef0c60, eventType=..., eventData=...)
    at /home/val/AGE/AtomicGameEngine/Source/Atomic/Core/Object.cpp:363
#10 0x00000000013a9762 in Atomic::Engine::Update (this=0x2ef0c60) at /home/AGE/AtomicGameEngine/Source/Atomic/Engine/Engine.cpp:730
#11 0x00000000013a90f8 in Atomic::Engine::RunFrame (this=0x2ef0c60) at /home/AGE/AtomicGameEngine/Source/Atomic/Engine/Engine.cpp:519
#12 0x00000000013ae966 in Atomic::Application::Run (this=0x2ef0610) at /home/AGE/AtomicGameEngine/Source/Atomic/Engine/Application.cpp:89
#13 0x000000000116e162 in RunPlayerApplication () at /home/AGE/AtomicGameEngine/Source/AtomicEditor/Application/Main.cpp:56
#14 0x000000000116e22b in main (argc=14, argv=0x7fffffffdec8) at /home/AGE/AtomicGameEngine/Source/AtomicEditor/Application/Main.cpp:180
```

**Comment by JoshEngebretson** [comment]
Thanks for the callstack and I didn't see your notes in #248 before commenting :)  Ok, cool that it is easy to reproduce, I'll have a look too and see if anything pops out

**Comment by JimMarlowe** [comment]
Yeah, I put in my notes into #248 after I did the PR, it was more typing. This must have been causing "mysteries in coding" for some people.

**Comment by JoshEngebretson** [comment]
Can exiting_ change between line 476 and the new check, something in BeginFrame? https://github.com/JimMarlowe/AtomicGameEngine/blob/967d4eccd2031fd6c57086167fb2821dddb33197/Source/Atomic/Engine/Engine.cpp#L476

**Comment by JimMarlowe** [comment]
The exiting_ gets asserted from within line 494, so the exit check at line 476 would only be hit if the line before it is triggered.

**Comment by JoshEngebretson** [comment]
Sorry, I am confoozled.  How can exiting_ change between line 476 and 498 (which is the new check)?

**Comment by JimMarlowe** [comment]
Since Engine::DoExit() is the only place that sets the exiting_ flag, then I'm going to hazard a guess that it is being changed by the HandleExitRequested event handler being fired off, and the event gets processed when it goes into ``time->BeginFrame(timeStep_);``. The only other path is, someone called Engine::Exit(), and this doesn't seem likely because of when the value changes.

**Comment by JimMarlowe** [comment]
The HandleExitRequested is being called, so events (and probably threads) are the answer.

**Comment by JoshEngebretson** [comment]
Excellent, thanks for verifying, would you mind adding a bit of commenting about this at 498, when reading the code it kind of induces a "Huh? Wha? Didn't we just check exiting_?" :)

**Comment by JimMarlowe** [comment]
I've added some more comments. Why do I always get the bizarre issues?

**Comment by JoshEngebretson** [comment]
Heh, because you're good at 'em 🐫 

Will land when green, thanks! ✔️

**Pull request merged**
