### PR TITLE
Revert "Dependency cleanup and IPC Server cleanup"

### PR DESCRIPTION
**Pull request by jmsmoorehead**

### CODE REVIEW

**Comment by mattbenic** [comment]
Why is this revert necessary? Also it's failing to compile on CI

**Comment by mattbenic** [comment]
Closing due to lack of response

**Comment by jmsmoorehead** [comment]
I'm just learning this josh sorry

**Comment by mattbenic** [comment]
No problem, we thought it might be a mistake :)

**Pull request closed without merging**
