### PR TITLE
Fixes for combined d.ts generation

### PR DESCRIPTION
**Pull request by shaddockh**
This PR fixes the issue with generating the combined ```Atomic.d.ts``` file under windows.  Tested on OSX as well to ensure that it didn't break anything.

### CODE REVIEW

**Comment by shaddockh** [comment]
Had to change things around.  Windows and OSX builds work from what I can tell, just need some verification.

**Comment by mattbenic** [comment]
Confirmed on windows, a lovely single ts distribution file :+1:

**Comment by shaddockh** [comment]
Ok. @JoshEngebretson, since this is breaking the build, I'm going to go ahead and land it.

**Comment by JoshEngebretson** [comment]
Thanks!  It was Lara's birthday in San Francisco yesterday and we're on a train back up to the Sierra Nevada's right now.  So, a tad out of position atm :)

**Comment by Type1J** [comment]
Happy Birthday @LaraEngebretson!

**Pull request merged**
