### PR TITLE
Issue #607

### PR DESCRIPTION
**Pull request by raheelx**
"Reveal in Finder" changes based on the platform being used. 

PS - Please test this for Mac and Linux as we're working with Windows

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Hi @raheelx , thanks for the PR! :)

@shaddockh is going to help do some code reviews on TypeScript related PR's, he should have notes for you soon

@AtomicBuildBot ok to test

**Comment by shaddockh** [comment]
Hey @raheelx, good work on this!  I was looking over the changes and have some suggestions on how to streamline it a bit and reduce some of the duplication. Typescript has a feature called ```computed keys``` that you can use on those associative arrays for the menu, so instead of needing to reconstruct both arrays based upon platform, you could do something like the following:
```
var showInFs = "Reveal in File Manager";
if (Atomic.platform == "Windows") {
  showInFs = "Reveal in Explorer";
} 
... more platforms ...
```

Then in your associative array do:
```
var assetGeneralContextItems = {
      "Rename": ["rename_asset", undefined, ""],
     [showInFs]: ["reveal_folder", undefined, ""],
     "-1": null,
    "Delete": ["delete_asset", undefined, ""]   
  };
```
The ```[showInFs]``` will get expanded at run-time to whatever value is contained in that variable.

Eventually, these menu structures will need to be refactored to be more extensible, but this should work for now.

**Comment by raheelx** [comment]
Hey @JoshEngebretson  and @shaddockh : )

Thanks for the tip! I just sent a new PR now with those changes :+1:

**Comment by shaddockh** [comment]
Awesome!!

@JoshEngebretson this looks good to me if you want to scan it and land it. :+1:

**Comment by JoshEngebretson** [comment]
Excellent, thanks guys! LANDING :airplane:

**Pull request merged**
