### PR TITLE
Replace the Ace editor with the Monaco editor

### PR DESCRIPTION
**Pull request by shaddockh**
This PR replaces the Ace editor with the Monaco editor from Microsoft.

Major changes:
* Replaces the Ace editor with the Monaco editor
* Adds live syntax checking for TypeScript and JavaScript
* adds live semantic syntax checking for TypeScript
* adds completions for JavaScript and TypeScript based upon code in project and d.ts files
* adds hovers for variables/methods in TypeScript and JavaScript
* adds parameter help for functions in TypeScript and JavaScript
* replaces the TurboBadger editor with Monaco editor with whitespace displayed (syntax highlighting, however, is not available.  A new grammar would need to be created, but if done could provide completions as well.)
* Supports application prefs for font size, themes ( vs or vs-dark supported), display whitespace, soft tabs, and tab size

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Hey, so the CI is failing on this:

```
[Sun Jul  3 22:23:49 2016] INFO: Loading Module: /Users/jenkins/Home/workspace/AtomicDS_BuildBinaries_MacPlayer/Script/Packages/WebView/WebView.json
[Sun Jul  3 22:23:49 2016] INFO: Generating JS Bindings
[Sun Jul  3 22:23:49 2016] INFO: Generating C# Bindings
error TS6053: File 'Script/TypeScript/AtomicNET.d.ts' not found.
error TS6053: File 'Script/TypeScript/WebViewWork.d.ts' not found.
```

I am not sure why it is only failing on MacPlayer and Linux, though others are passing.

**Comment by JoshEngebretson** [comment]
Oh,  I cleaned the CI workspaces too, I can look into this tomorrow if it doesn't add up... looking forward to having a gander at the code too :)

**Comment by shaddockh** [comment]
That's really strange.  I thought maybe it was a filename casing issue, but everything looks correct.  Is there a way to get a trace to determine where exactly it's failing?  It's odd that the mac builds, but the mac player does not.  Is either something getting purged between builds or is the current working directory getting changed somehow so relative paths to line up?

**Comment by JoshEngebretson** [comment]
No worries, looking into it and will report.  I know AtomicNET shouldn't be a thing on master, WebViewWork.d.ts a crumb reference as well?

**Comment by JoshEngebretson** [comment]
They are being added to the tsconfig by the merge, here:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/TSH-ATOMIC-MONACOEDITOR/Script/tsconfig.json#L106

and here:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/TSH-ATOMIC-MONACOEDITOR/Script/tsconfig.json#L114

Not entirely sure why only these 2 platforms are barfing, though good some are as should be removed... yay? :)

**Comment by shaddockh** [comment]
Probably should be removed. I'm away from my computer but can look at it tomorrow.

**Comment by JoshEngebretson** [comment]
I removed them, somehow references being added to main.ts on these builds: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/TSH-ATOMIC-MONACOEDITOR/Script/AtomicEditor/main.ts  bizarre

**Comment by JoshEngebretson** [comment]
Something about how the CI is checking out the PR, which is causing a problem with the Mac and Linux CI, though not others... I can see wrong files in the checkout.  I don't think there is anything for you to do here, though I won't be able to build test editor builds until I figure it out.

**Comment by shaddockh** [comment]
FYI, I think those files will need to be specifically set to not be included within the filesglob section. Otherwise Atom will keep adding them back in on edit.

**Comment by JoshEngebretson** [comment]
They are gone and should not come back, unless they explicitly make a return.  I just built out editor distro binaries to test, so far so good!

**Comment by JoshEngebretson** [comment]
Ok, testing on OSX and the editor view is white and it can't be edited.  Can be reproduced with a ./Build_AtomicEditor.sh editor artifact here.  No rush, lemme know if it reproduces for you... 

screen shot 2016-07-04 at 6 13 44 pm

**Comment by shaddockh** [comment]
ok, this had to do with the old Ace editor settings getting set in your application preferences file and Monaco trying to load an invalid theme.  The latest commit fixes this, but you may need to remove the "codeEditorSettings" block from you application settings file ( it won't be looked at, but for cleanup you'll want to remove it).  The settings now look at the "codeEditor" block.

**Comment by JoshEngebretson** [comment]
Awesome, the mighty @LaraEngebretson is testing this morning :)

**Comment by JoshEngebretson** [comment]
This is fantastic!  Monaco is really nice looking and super snappy, more responsive than Ace.  Intellisense is also really solid.  Great work, going to make a gif for tweet-age :)  LANDING! Thanks! :airplane:

**Pull request merged**
