### PR TITLE
Scene view 3d move camera with the middle mouse move

### PR DESCRIPTION
**Pull request by balmacefa**
use the same funcionality as the Q,E,A,D Keys to move the camera. @JoshEngebretson @rosshadden

### CODE REVIEW

**Comment by balmacefa** [comment]
@JoshEngebretson,The lines are indented

**Comment by JoshEngebretson** [comment]
@balmacefa I'll give this a try a bit later and see if we can sneak it in for Build 3, looks cool

**Comment by JoshEngebretson** [comment]
@AtomicBuildBot ok to test, add to whitelist

**Comment by JimMarlowe** [comment]
The functionality for this PR is ok. The only problem I encountered in it's use, was from the camera speed.  It has no visible setting to show the user what it is, and is set by the right mouse button + mousewheel, according to https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Scene-Editor-Hotkeys. With no feedback that it is mouse speed is changing, you can do so, and then moving with camera with the middle mouse button can change dramatically, with no obvious way to recover the old setting.

**Comment by balmacefa** [comment]
I propose a UI indicator of the status of the view https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1330 , maybe we can include a speed indicator

**Pull request closed without merging**
