### PR TITLE
tweak the CEF resources files copy bit

### PR DESCRIPTION
**Pull request by CTrauma**
Trying to remove some noise from the log. CEF was complaining about missing files. This change will pick them up.

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Interesting, the CEF3 cmake scripts on Windows/OSX set this copy stuff up using CEF3's scripts: 

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/AtomicEditor/CMakeLists.txt#L130

Can this be done here for Linux  instead?  I'd like to do a little cleanup for where the CEF3 is used in a binary, there's a bit too much fluff, even if most of it is hidden in macros.

**Comment by CTrauma** [comment]
I'll have a look to see what can be done, cleanup is always good.

**Comment by CTrauma** [comment]
Accidentally added my latest commit to this open PR, let me know if you want me to move it elsewhere or if you just want to cherry pick the commit 2bfc09b

**Comment by JoshEngebretson** [comment]
Hey @CTrauma Yeah, I'll close this PR and let's open a new one with the fix.  Thanks!

**Pull request closed without merging**
