### PR TITLE
UI enhancements and color picker

### PR DESCRIPTION
**Pull request by JimMarlowe**
UI enhancements for #379 and #914

Added AccentColors elements to the light/dark skins, and used them to replace hex code colors in editor tb.txt files.
Replaced stock TB checkboxes in both skins with a blue square check box, fixed some instances when the UI files were referencing the grayed checkbox instead of the normal checkbox.
Replaced window and tab closer X in both skins with something better looking.
Added tooltips to the top editor icons for Translate, Rotate, Scale, and the Local/World button.
Created TBColorWidget and TBColorWheel widgets for use in the color picker
Added UISlider, UIColorWidget and UIColorWheel Atomic widgets, to make them scriptable.
Added a simple color picker to the color inspector.

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Really great work, I went over the entire pull and looks good.  Nice job figuring out some of the more esoteric UI stuff, especially things like event blocking for changed notifications (so you don't end up filling up a ton of undo levels) and getting new widgets written and others wrapped :+1: 

My only comment is wondering if the dark theme should avoid using a bright-ish blue for checkboxes and sliders, I know there was some legacy usage of this from the original TB theme.  We can live in it for a bit and see what people think.  I like the changes to the close X :)  

I'll build out the branch here once I have a couple more things done for today, then land it.  THANKS!

**Comment by JoshEngebretson** [comment]
A couple notes from testing:

I opened up a color chooser on global light color setting and chose red:

choosered

When I hit ok, the inline select fields of  the light color did update however the light component itself was not updated, this is probably due to blocking change events or an edit complete not getting caught, not sure.

notupdated

When a color chooser is open, clicking the '...' button will open additional choosers, it should maybe be disabled until the associated chooser closes.

multichoosers

**Comment by JimMarlowe** [comment]
I'll make it so you cant bring up more than one color chooser at a time.
I was wondering if I should send an edit complete event, it looks like yes, I'll do that too.

**Comment by JimMarlowe** [comment]
I still have to make it only bring up only one color chooser at a time, but I finally got the color to apply. Though it only took 4 additional lines, the path to get there was interesting to say the least. And I added HSL text, by request.

**Comment by JoshEngebretson** [comment]
Great, I'll have a quick stab this morning to see if can get the edit event down to one, otherwise will be 4 levels of undo I believe.  It would also be good to get the '...' button justified to the right for consistency and to save vertical space

**Comment by JimMarlowe** [comment]
These are skin changes for the checkbutton, radiobutton, and slider thumb. No more blue.

**Comment by JoshEngebretson** [comment]
Very cool, if you merge https://github.com/JimMarlowe/AtomicGameEngine/pull/1 those changes will show up here too

**Comment by JoshEngebretson** [comment]
Great work, made a PR with combined updates, will land from there :airplane:  : https://github.com/AtomicGameEngine/AtomicGameEngine/pull/920

Thanks!

**Pull request closed without merging**
