### PR TITLE
Toggle to Play camera

### PR DESCRIPTION
**Pull request by balmacefa**
press C key to change between the __atomic_sceneview3d_camera and scene camera. Select a camera and press C to chage to that camera, if you dont select a camere, we change to the first camera compoment in the scene, if there is no camera switch to default (__atomic_sceneview3d_camera), lock the camera pos, rot with L key. Every time it is passed to a user's camera, it is blocked

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Thanks for the pull requests, will have a look at them soon

**Comment by Alan-FGR** [comment]
@JoshEngebretson may need some refactor for capitalization and also the tabs :P. Not too sure on naming too, maybe could be more descriptive. Also, I don't see the need to maintain a bool separately for that @balmacefa. Isn't it better to just check if the editor camera is being used every time since you have actualCameraNode_? Just some random thoughts, otherwise good work!

**Comment by Alan-FGR** [comment]
I also don't see the need for the lookCamera_... can't we just check that in L297? I mean, just check if the actualCameraNode_ is the defaultCameraNode_ and you don't need those bools at all... btw, I recommend changing those var names to something like 'activeCameraNode' or 'currentCameraNode' and 'sceneCameraNode' or something else more descriptive. I really couldn't tell right away what those are for.

**Comment by Alan-FGR** [comment]
Also, we got hardcoded keys all over the place :P.

**Comment by balmacefa** [comment]
Sorry for the naming of the variables, my English is bad :(, the reason I use the lockcamera boolean is if you want to move the camera (user once) for better framing, but I think is usedful to move it just we you wanna to. The actualCamera var is a dirty solution, to avoid saving the pos rot of the user's camera, if you change the cameraNode_ and save the scene in a user camera, it take like is the default camera

**Comment by balmacefa** [comment]
Maybe if you received a event went the scene is saved, we can change the cameraNode_ ref to the default

**Comment by Alan-FGR** [comment]
@balmacefa No need to apologize man! It's just constructive criticism :). Let's wait for further input from @JoshEngebretson then.

**Comment by JoshEngebretson** [comment]
@balmacefa This looks like really interesting functionality, I hadn't thought of using the scene camera like this, is this inspired by an existing 3D package?  

Before reviewing in earnest, would you mind having a look over the [C++ code conventions](https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Coding-Conventions-(CPlusPlus)) and make sure that the contributions follow the brief guidelines.  For example, one thing I notice is that it looks like the code has soft tabs (this is a common issue if you haven't run into it before).

Thanks.

**Comment by balmacefa** [comment]
Sure I can change that and amend to the last commit,  I suggest you add a link of c++ convention to CONTRIBUTING. This functionality is present in blender and in deferent way in unity, they use another tab.

**Comment by JoshEngebretson** [comment]
@balmacefa Thanks, I just posted the C++ conventions and that is a very good suggestion on the ```CONTRIBUTING``` doc. I'll move the information to the wiki and then link that in the CONTRIBUTING file, as it is easy to forget to update that one.  

Maybe someone will solve whitespace in our time? :)

**Comment by balmacefa** [comment]
@JoshEngebretson The lines are indented, i make cleared implementation https://github.com/balmacefa/AtomicGameEngine/commit/022bfc961b541b3e47308889f951e686d6f959c4, but i do not know what you think, maybe insted of change the method to virtual (https://github.com/balmacefa/AtomicGameEngine/commit/022bfc961b541b3e47308889f951e686d6f959c4#diff-5b9c5e06c291aa111d6451d1fe3f2386R93), we can change the ptr to the defaultCamera in https://github.com/AtomicGameEngine/AtomicGameEngine/blob/c15b882d495fd6960478e958dd2c4301d5413027/Source/AtomicEditor/Editors/SceneEditor3D/SceneEditor3D.cpp#L256, this is to avoid save the user camera data(pos, rot)

**Comment by JoshEngebretson** [comment]
@balmacefa It is looking better 👍 ,  we're currently getting the Build 3 binary release prepared (I still have one major issue in the works for it, finishing it up today).  I'd like to get the camera functionality factored in soon after the build ships.

BTW, good suggestion on updating [CONTRIBUTING.md](https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/CONTRIBUTING.md), I  added a link to developer info, including  C++ code convention page: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Coding-Conventions-(CPlusPlus)

I noticed that GitHub smartly links the document when making new PR's, issues, etc, the developer info is a start and can be spruced up 🌲 

Thanks!

**Comment by JimMarlowe** [comment]
This is an interesting feature, but it must have some UI feedback. Once the 'L' gets triggered, the camera is frozen. This can be done by pressing the 'L' and when you press 'C' to switch cameras the first time. With no locked indicator, you think the editor is broken.  It could really stand reporting which camera you are using also. Only supporting the 1st camera is hardcoded, is there no value in having more than one camera? If there is none, then this is fine. There is a oddity, when you have a camera selected and then you select the camera in the hierarchy view, you sometimes get a blue square, I've seen a big one and a smaller one, then it can disappear. 
bluebox-1329

**Pull request closed without merging**
