### PR TITLE
Expose Renderer2D to script

### PR DESCRIPTION
**Pull request by mattbenic**

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
I guess Renderer2D was the unknown component :)  Renderer2D is an internal class (self creates when needed and has no useful user API), thinking should use this as an opportunity to improve the error handling to report the unexposed class and not throw.  We should filter in this case, as we don't want to require all native components be registered with script bindings.

I'll work on this today.

**Comment by mattbenic** [comment]
Doh, yeah sorry should have had the Renderer2D one in a separate feature branch. I'll get those into separate feature branches for you tomorrow.

**Comment by JoshEngebretson** [comment]
That's ok, see my note on Renderer2D above, I'll address this today.

**Comment by mattbenic** [comment]
Saw that, thanks. I'll replace our band-aid with the proper fix

**Pull request closed without merging**
